FROM <%= conf.dockerRepo %>/angular2

COPY ./package_project.json /app/package_project.json
COPY ./bower.json /app

# install_dependencies will merge deps in the container
RUN docker_scripts/install_dependencies /app/package_project.json && \
  rm /app/package_project.json && \
  yarn && \
  bower install --silent --allow-root

# Don't modify these lines - END
COPY ./src/dll /app/config/dll
RUN echo "APP_ENV=development" > /app/.env
RUN npm run build:dll
# Don't modify these lines - START :)
