FROM garlictech2/workflows-library:<%= conf.dockerWorkflowVersion %>

# These lines should not be changed
ARG NPM_TOKEN
COPY ./package.json /app/package_project.json
RUN scripts/install_dependencies
COPY src /app/src/
