FROM <%= conf.dockerRepo %>/workflows-library:<%= conf.dockerWorkflowVersion %>

# install_dependencies will merge deps in the container
COPY ./package.json /app/package_project.json
RUN scripts/install-project-dependencies.sh package_project.json
