#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
hooks/travis/hooks_base-generated script

# ADD YOUR PARTS HERE
npm run unittest

if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
  echo "e2etest skipped!"
else
  npm run e2etest
fi
