FROM <%= conf.dockerRepo %>/angular2-webapp

COPY ./package.json /app/package_project.json
COPY ./bower.json /app

# install_dependencies will merge deps in the container
RUN scripts/install-project-dependencies.sh package_project.json

#  bower install --silent --allow-root
