FROM garlictech2/angular2-webapp:<%= conf.dockerWorkflowVersion %>

# These lines should not be changed!
ARG NPM_TOKEN
COPY ./package.json /app/package.project.json
# We need the copy for the proper installation of the submodule dependencies.
COPY src /app/src/
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc && \
  scripts/install_dependencies
