#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
npm run travis script

# ADD YOUR PARTS HERE
npm run ngx:build:dev
npm run setup
npm run lint
npm run ngx:unittest
npm run ngx:build:prod

npm run backend:build
npm run backend:unittest
