FROM <%= c.dockerRepo %>/<%= c.workflowsServerType %>:<%= c.dockerWorkflowVersion %>

COPY package.json /app/package_project.json
# install_dependencies will merge deps in the container
RUN scripts/install_dependencies package_project.json
