#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
npm run travis script

# ADD YOUR PARTS HERE
npm run build:dev
npm run setup
npm run lint
npm run unittest
npm run build:prod

if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
  echo "e2etest skipped!"
else
  npm run e2etest
fi
