#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
hooks/travis/hooks_base-generated script

# ADD YOUR PARTS HERE
npm run travis unittest
npm run travis systemtest
make start-d
make smoketest
make kill-all
