angular = require 'angular'
require 'angular-animate'
require 'angular-aria'
require 'angular-material/angular-material.scss'
require 'angular-material'
require 'font-awesome-webpack'
require 'angular-material-icons'
